package management

import (
	"testing"
)

func TestVerifyPayOSSignature(t *testing.T) {
	checksumKey := "4b79b69e12f73459af9559fcc188fd3197aa1e8eb72507897c2e7883f3ecdd1f"

	data := map[string]interface{}{
		"orderCode":              123,
		"amount":                 3000,
		"description":            "VQRIO123",
		"accountNumber":          "12345678",
		"reference":              "TF230204212323",
		"transactionDateTime":    "2023-02-04 18:25:00",
		"currency":               "VND",
		"paymentLinkId":          "124c33293c43417ab7879e14c8d9eb18",
		"code":                   "00",
		"desc":                   "Thành công",
		"counterAccountBankId":   "",
		"counterAccountBankName": "",
		"counterAccountName":     "",
		"counterAccountNumber":   "",
		"virtualAccountName":     "",
		"virtualAccountNumber":   "",
	}

	// Signature generated by our test_payos_webhook.js script using the same data and checksumKey
	expectedSignature := "b43e37465a041ff410a4e23b0543add84b3fead12d9894a22996d776d1e40fa4"

	if !verifyPayOSSignature(data, expectedSignature, checksumKey) {
		t.Errorf("verifyPayOSSignature failed. Expected true for matching signature.")
	}

	// Test invalid signature
	invalidSignature := "a43e37465a041ff410a4e23b0543add84b3fead12d9894a22996d776d1e40fa4"
	if verifyPayOSSignature(data, invalidSignature, checksumKey) {
		t.Errorf("verifyPayOSSignature failed. Expected false for invalid signature.")
	}
}
